name: API Request
description: Create an API request for Quilt Standard Libraries.
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your API request! If you want to discuss your feature request, join us on [Discord](https://discord.quiltmc.org).

  - type: textarea
    id: description
    attributes:
      label: Describe how your feature(s) will work if applicable.
      description: "Describe what you want QSL to implement as clearly as possible. More info means your request is more likely to be accepted."

  - type: textarea
    id: library-or-module
    attributes:
      label: Where does your API fit into QSL's structure? Which library and module? Does this add a new library or module?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about your API request here."
