name: Publish Snapshot
on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Check Licenses and Generate QMJs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkLicenses generateQmj --parallel --stacktrace
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') && !startsWith(github.ref, 'refs/tags/v') }}
      - name: Publish to Snapshot maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish --stacktrace --parallel
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') && !startsWith(github.ref, 'refs/tags/v') }}
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*/build/libs/
